### PR TITLE
add Python version

### PR DESCRIPTION
**Pull request by xtfer**
Add a .python-version file to work with pyenv.

### CODE REVIEW

**Comment by Crell** [comment]
@NickAnderegg I defer to you here.  Merge if you're happy.

**Comment by demosdemon** [comment]
++

**Comment by demosdemon** [comment]
Wait. We don't have 3.7.2 in our images yet. I'd change it to 3.7.0 to match platform or convince engineering to update python.

**Comment by demosdemon** [comment]
Alternatively, change it to `3.7` and let pyenv figure it out.

**Comment by xtfer** [comment]
@demosdemon This only applies in local development. This project never actually runs on our services.

**Comment by demosdemon** [comment]
> @demosdemon This only applies in local development. This project never actually runs on our services.

Right, I understand this; however, it's good to make your local development environment as close as possible to the production environment to avoid any inconsistency related bugs.

**Comment by xtfer** [comment]
@demosdemon You are correct, but this project is only ever run in a local environment – its a builder for the template-* project. It has no production environment.

**Comment by demosdemon** [comment]
Woah. Ignore me. I totally misinterpreted this.

**Pull request merged**
